audio-pitch-correction=yes
hwdec=auto-safe
vo=gpu
profile=gpu-hq


[lecture]
af=scaletempo2,lavfi=[highpass=f=80, lowpass=f=8000]
audio-tempo-match=exact
video-sync=display-resample
interpolation=yes
tscale=oversample

[lecture-fast]
af=rubberband=tempo=yes:pitch=yes:transients=enhance,lavfi=[highpass=f=50, lowpass=f=10000]
audio-pitch-correction=yes
video-sync=display-resample

[high-speed]
speed=4.0
af=scaletempo2=max-speed=100, lavfi=[highpass=f=100, lowpass=f=8500, dynaudnorm=f=250:g=11:m=15:p=0.95]
vf=cas=0.35
video-sync=display-resample
interpolation=yes
tscale=oversample
audio-pitch-correction=yes

[anime]
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
deband=yes
deband-iterations=2
deband-threshold=32
deband-range=16
interpolation=no
video-sync=audio
sub-scale=1
sub-ass-override=force
af=
audio-pitch-correction=no
